In [2]:
import numpy as np

In [3]:
test5 = np.array([[[[ 1,  2],
   [ 3,  4]],

  [[ 5, 6],
   [7, 8]]],


 [[[ 9, 10],
   [ 11, 12]],

  [[13,  14],
   [15, 16]]]])
test5

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [4]:
test5.shape

(2, 2, 2, 2)

In [5]:
test51 = test5.reshape(test5.shape[0],test5.shape[1],-1)
test51

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [6]:
zer1 = np.zeros((test5.shape[0], test5.shape[1], test5.shape[2]))
zer1

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
test52 = np.append(test51, zer1, axis=2)
test52

array([[[ 1.,  2.,  3.,  4.,  0.,  0.],
        [ 5.,  6.,  7.,  8.,  0.,  0.]],

       [[ 9., 10., 11., 12.,  0.,  0.],
        [13., 14., 15., 16.,  0.,  0.]]])

In [8]:
test53 = np.append(zer1, test52, axis=2)
test53

array([[[ 0.,  0.,  1.,  2.,  3.,  4.,  0.,  0.],
        [ 0.,  0.,  5.,  6.,  7.,  8.,  0.,  0.]],

       [[ 0.,  0.,  9., 10., 11., 12.,  0.,  0.],
        [ 0.,  0., 13., 14., 15., 16.,  0.,  0.]]])

In [9]:
zer2 = np.zeros((test53.shape[0], 1, test53.shape[2]))
zer2

array([[[0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.]]])

In [10]:
test54 = np.append(test53, zer2, axis=1)
test54

array([[[ 0.,  0.,  1.,  2.,  3.,  4.,  0.,  0.],
        [ 0.,  0.,  5.,  6.,  7.,  8.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  9., 10., 11., 12.,  0.,  0.],
        [ 0.,  0., 13., 14., 15., 16.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

In [11]:
test55 = np.append(zer2, test54, axis=1)
test55

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  2.,  3.,  4.,  0.,  0.],
        [ 0.,  0.,  5.,  6.,  7.,  8.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  9., 10., 11., 12.,  0.,  0.],
        [ 0.,  0., 13., 14., 15., 16.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

In [12]:
test55.reshape(test5.shape[0], test5.shape[1]+2, test5.shape[2]+2, test5.shape[3])

array([[[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 1.,  2.],
         [ 3.,  4.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 9., 10.],
         [11., 12.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [13., 14.],
         [15., 16.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]]])

In [13]:
test5 = np.array([   [[[ 1,  2],
                       [ 3,  4]],

                      [[ 5, 6],
                       [7, 8]]],


                     [[[ 9, 10],
                       [ 11, 12]],

                      [[13,  14],
                       [15, 16]]]])
test5

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [15]:
padding = 1
batch, row, col, chanel = test5.shape
zer1 = np.zeros((batch, row, padding, chanel))
zer1

array([[[[0., 0.]],

        [[0., 0.]]],


       [[[0., 0.]],

        [[0., 0.]]]])

In [16]:
test5 = np.append(test5, zer1, axis=2)
test5 = np.append(zer1, test5, axis=2)
test5

array([[[[ 0.,  0.],
         [ 1.,  2.],
         [ 3.,  4.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 9., 10.],
         [11., 12.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [13., 14.],
         [15., 16.],
         [ 0.,  0.]]]])

In [17]:
new_col = col + padding * 2
zer2 = np.zeros((batch, padding, new_col, chanel))
zer2

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [18]:
test5 = np.append(test5, zer2, axis=1)
test5 = np.append(zer2, test5, axis=1)
test5

array([[[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 1.,  2.],
         [ 3.,  4.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 9., 10.],
         [11., 12.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [13., 14.],
         [15., 16.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]]])

In [19]:
test5[:, padding:-padding, padding:-padding, :]

array([[[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]]],


       [[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]])